# render.yaml - Blueprint for Render.com deployment
services:
  # Web service for Django application
  - type: web
    name: portfolio-django
    env: python
    buildCommand: |
      # Install dependencies
      pip install -r requirements.txt
      # Run migrations
      python manage.py migrate
      # Collect static files
      python manage.py collectstatic --noinput
      # Create superuser
      python -c "import os; from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser(os.environ.get('DJANGO_SUPERUSER_USERNAME'), os.environ.get('DJANGO_SUPERUSER_EMAIL'), os.environ.get('DJANGO_SUPERUSER_PASSWORD')) if not User.objects.filter(username=os.environ.get('DJANGO_SUPERUSER_USERNAME')).exists() else None"
    startCommand: gunicorn portfolio_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: portfolio_project.settings_prod
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        sync: false # Prompt for value on first deploy
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-db
          property: connectionString
      - key: DJANGO_SUPERUSER_USERNAME
        sync: false # Prompt for value on first deploy
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false # Prompt for value on first deploy
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false # Prompt for value on first deploy

# PostgreSQL database
databases:
  - name: portfolio-db
    plan: free # Change to a paid plan for production
    ipAllowList: [] # Allow all IPs by default