# render.yaml - Blueprint for Render.com deployment
services:
  # Web service for Django application
  - type: web
    name: portfolio-django
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn portfolio_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: portfolio_project.settings_prod
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        sync: false # Prompt for value on first deploy
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-db
          property: connectionString

# PostgreSQL database
databases:
  - name: portfolio-db
    plan: free # Change to a paid plan for production
    ipAllowList: [] # Allow all IPs by default